### PR TITLE
New graphs added, trailingSlash fixed

### PR DESCRIPTION
**Pull request by atharvu1**
Graphs added, Trailing-slash fixed, kaggle api added, data updated

### CODE REVIEW

**Comment by Cryptonex7** [comment]
# Request Halted For 1 Hour
- Waiting for Kaggle-API to Trigger 
- Checking API Integration with Kaggle API

**Comment by atharvu1** [comment]
Ignore

**Comment by atharvu1** [comment]
Ignore

**Comment by atharvu1** [comment]
Auto-update in 'master' is 60 seconds, merge it with 'new-updates'.

**Review by Cryptonex7 — COMMENTED** [review]
Dont know what to do here XD

**Pull request closed without merging**
